language: go
go:
  - '1.x'
os:
  - linux
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:wireguard/wireguard
  - sudo apt-get -yq update
  - sudo apt-get -yq install linux-headers-$(uname -r) wireguard-dkms
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/lint/golint
insstall:
  - dep ensure -v
script:
  - go build .
  - go vet ./...
  - golint -set_exit_status $(go list ./... | grep -v vendor/)
  - sudo env "PATH=$PATH" go test -v ./...
