language: go

go:
  - 1.x

os:
  - linux

env:
  global:
    secure: emnRsBTHNNiMUzB/sXtLlLxc1wStTFjl1eCxCPgp/SIHjVFDYrjdyaTzQDhzdpfxVb1xrLTp7ND5gfc3v4/7Oj5BCRtBn8p/HxMdIogCy2ciZa13khFJwDCMfOwxesHzhxjCyVdJIsu9RuR8dLfgy/0MT120icwk/G/ipKzQgpMrw+YTe59jXsRPOUDxas+foka02vqJtbJyHj1hh4kqnK2DfTAu4puSmmKdXV1UvLhUwDqXoeDtp5I9WoVmSDQBVcDsaESdjD4+TcMOVd3jJM8NsP4kdW7Oa5cHd+0vJtAeJtzjB8346knEiuqa98FahbMmy4dL15BqPnyT8BrSf3ZqoMTrcbeVridpT+qowxcqzaprU46bWks6fi2UYJnw1AY6IeADMoiSks1f6IoGCaDaFbsLr3MiUDQHxv2UZfmksNvvpyU0R7EhW5K8876Ik3DLXOMP46mJtN91aw7LRGwwUU8fJE9dftO0lTbsiCPtWKX+gHdlRdz9iudwmNRK9w6r2R7IubIahc0o2tOnk8Lr6ZzF1RXng6uVnKvChMLwSqr0Uvl2g+2gNyAwy0zA7aubH1kHpkIx3Y9wgbRm1EvlsxhLbAZZ+aibggFOOiVwIASBmoXfqnh20GY2TJcSB7dm03MgTRlQ291QvSXvMpTD1Vto7prRvXM48b2HUYg=

before_install:
  - sudo add-apt-repository -y ppa:wireguard/wireguard
  - sudo apt-get -yq update
  - sudo apt-get -yq install linux-headers-$(uname -r) wireguard-dkms
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

script:
  - go get
  - go vet ./...
  - golint -set_exit_status $(go list ./... | grep -v vendor/)
  - sudo env "PATH=$PATH" go test -v -cover -coverprofile cover.out ./...
  - sudo env "PATH=$PATH" goveralls -service=travis-ci -repotoken=$COVERALLS_TOKEN -coverprofile=cover.out
  - go build .

before_deploy:
  - RELEASE_MESSAGE="$(git tag -ln --format '%(subject)' $TRAVIS_TAG)"

deploy:
  provider: releases
  name: $TRAVIS_TAG
  body: $RELEASE_MESSAGE
  file: wgctl
  overwrite: true
  on:
    tags: true
  token:
    secure: I+ZBv7vBWmVphrB2HNpV+ksMoJNbQ0W9rhy+G9m3ajDa1wPm/t+XZ1G4Kgr7Kh3zHEt3slbYK5mRbidYXwVunVUt4edH62DxgD9Ofz6s7mnRhBiNCBn07rGVYVuebeX//lq2+2m2kj+zJ1nFE5/PJDLqWkoMzOsT5R615tKOHwlbnk9L0C0J2UpcZREsfEBCeS9Nvss2Lp2k1CCWnLA0yZOf0zTrCN38KB582ucht6G2+58nu3Ewmp7JH/2mMAcf5SZ3Eho76Hqmm9jWyvQXJ5XxvO4zz+6QcxPX+uU8J5kcl35Ij+591aLD3yPfxMVmXK5cNkh0vNQols36QZ0jD2lCjlin+jfNPpDsGk4Xa2+DhompCddv4/aOYV6rStSYopoOYau+9eXm+M1JRu+n7J5EGsF1qGdpeVcPATu54MfqS8EvdoMp6rP/zVyKer/VM2rUCtUKbxmBlmgKZT+KCsvk++2QiKbOnl1zShwXwyguG7cOTaUdxiUZqNcUv/o40joPHZ3QoG/LB8IDLv1okgDh7r3m3bUNBYG6tBYvHABOtYimT7vea+d3XQO+5wYStxW7ACFTZmbHuzEcaRjzHQZL4ZT2mVgxk0EsGy0GiAP+U7c6jBGZYInFK25TDNCNXpSRyAVswt4/hoq6RARrOnIGHeLHbKQQwKXbstJ75kU=
